<template>
    <div class="workExperience">
        <h5 class="section-header">Pengalaman Kerja: <span><a href="#"><i class="fa fa-plus-circle" aria-hidden="true"></i> Tambahkan Pengalaman Kerja</a></span></h5>
        <ul> 
            <li v-for="myExperience in experience" v-bind:key="myExperience.id" class="experience">
                <div class="position-relative">
                    <h4> {{myExperience.name}} <span><a href="#"><i class="fa fa-pencil-square" aria-hidden="true"></i> Edit</a></span></h4>
                    <h5> {{myExperience.company}}</h5>
                    <h6> {{myExperience.date}} ({{myExperience.duration}})</h6>
                    <br>
                    <p>
                         {{myExperience.description}}
                    </p>
                </div>
            </li>
        </ul>                 
    </div>
</template>

<script>

export default {
    name: 'workExperience',
    data: function() {
        return {
            experience: [
                {
                    id: 1,
                    name: 'Fresh Graduate Academy - Machine Learning Trainee (2019)',
                    company: 'Digital Talent Scholarship (KOMINFO)',
                    date: 'September 2019 - November 2019',
                    duration: '2 months',
                    description: 'One out of thousands of applicants who got accepted and received Machine Learning training from the Indonesia Ministry of Communication and Information Technology (KOMINFO). This training is a collaboration between the Indonesia Ministry of Communication and Information (KOMINFO).'
                },
                {
                    id: 2,
                    name: 'Database Management Intern',
                    company: 'Badan Meteorologi Klimatologi dan Geofisika',
                    date: 'July 2018 - September 2018',
                    duration: '2 months',
                    description: 'Responsible for managing and analyzing the database of rain intensity data from Pondok Betung Tangerang Climatology Station. Also responsible for comparing rain intensity data generated by Hellmann Rain Gauge and Automatic Rain Gauge as a consideration for a replacement in rain gauge instrument.'
                }
            ]
        };  
    },
}
</script>


<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss" scoped>
</style>